Add Dz Code Academy and fixed a typo
algeriatech/awesome-algeria pull request #5
Opened 2017-01-09 22:01 UTC by Ilyes-Hammadi

2017-01-09 22:25 UTC, IOAyman requested changes
/cc @youknowriad

2017-01-09 22:25 UTC, IOAyman commented on README.md
> +- [DZ Code Academy](https://github.com/Ilyes-Hammadi/dz-code-academy) - Learn to code in Arabic (Algerian dialect)
This looks like an empty repo pointing to a YouTube channel and missing a license.
Why not link the channel directly in a new _Educational Material_ section, or something like that?

PS: Correct me if I am wrong, but this repo will contain some course material, right? If so, then I don't think it should be included at all.

Last but not least, I do love the work you've done over at that channel! 😉

2017-01-09 22:30 UTC, Ilyes-Hammadi commented on README.md
> +- [DZ Code Academy](https://github.com/Ilyes-Hammadi/dz-code-academy) - Learn to code in Arabic (Algerian dialect)
@IOAyman Thanks for the kind words. Yeah you are right i am gonna replace the link to the empty repo by including the youtube channel link in a new section like you suggested, i like the one you proposed.

2017-01-10 07:51 UTC, youknowriad commented
I'm not sure how I feel about this, These videos are awesome but it's not really a library or a software. Thus, this does not match the requirements and this list is not made for this kind of things.

2017-01-10 07:52 UTC, youknowriad commented
BTW, If you could extract the typo fixo in a separate PR, I'd be happy to merge it

2017-01-10 08:06 UTC, Ilyes-Hammadi commented
Okey, I totally understand. I am gonna extract the typo changes into a separate PR.

2017-01-10 08:07 UTC, IOAyman commented
@youknowriad, I've also thought about that point, but then I said to myself "I've seen other _awesome-*_ lists containing links to various great courses and books on different platforms .. So why not this one".

2017-01-10 08:14 UTC, youknowriad commented
Yeah, I'm really hesitant here. Let's keep this PR open for a while. Maybe if we notice more similar projects, we could create a dedicated section or even a dedicated file.

2026-03-09 23:57 UTC, closed without merging