Add awesome open minds and Tchamba (pip package)
algeriatech/awesome-algeria pull request #6
Opened 2017-01-09 22:01 UTC by Fcmam5

2017-01-09 22:06 UTC, IOAyman requested changes
Please rebase on `upstream/master`

2017-01-10 07:48 UTC, youknowriad requested changes
Thank's for the PR. These Repositories are awesome!. I like the name "Tchamba", Genius! :) 

Though make sure to reorder `awesome-open-minds` and rebase your branch.

2017-01-10 07:48 UTC, youknowriad commented on README.md
> +- [awesome-open-minds](https://github.com/open-minds/awesome-openminds-team) awesome useful links, resources and shiny things for CS students, geeks and developers
Could you move this to the top of the "other" category (to keep an alphabetical order).

2017-01-10 14:37 UTC, Fcmam5 commented
thank you @IOAyman, @youknowriad . Done

2017-01-10 14:39 UTC, IOAyman commented
Only a step more...
```bash
git remote add upstream https://github.com/youknowriad/awesome-algeria.git && git rebase upstream/master
```

2017-01-10 14:41 UTC, Fcmam5 commented
I did that, and I still seeing that there's a conflict

2017-01-10 14:42 UTC, youknowriad commented
@Fcmam5 `git fetch upstream` before the rebase

2017-01-10 14:43 UTC, IOAyman commented
`git fetch` before rebasing then

2017-01-10 14:53 UTC, youknowriad commented
There's no conflict now, but you did not resolve the conflicts properly :) Make sure to correct your PR changes :)

2017-01-10 14:55 UTC, Fcmam5 commented
Sorry I messed it up, fixed now. Thank you

2017-01-10 14:56 UTC, IOAyman approved these changes

2017-01-10 14:56 UTC, youknowriad approved these changes

2017-01-10 14:57 UTC, merged

2017-01-10 14:58 UTC, youknowriad commented
Thanks for the contribution @Fcmam5 feel free to join https://github.com/youknowriad/awesome-algeria/issues/7